### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by thenhthang** [make-software/casper-net-sdk#10]
room@Rooms-MacBook-Pro caspertest1 % dotnet add CasperTest1 package Casper.Network.SDK --version 0.9.4-beta
  Determining projects to restore...
  Writing /var/folders/kb/v9pqm1312tv73dv25dxvcw240000gn/T/tmpP2WN6V.tmp
info : Adding PackageReference for package 'Casper.Network.SDK' into project '/Users/room/Projects/CasperTest1/CasperTest1/CasperTest1.csproj'.
info : Restoring packages for /Users/room/Projects/CasperTest1/CasperTest1/CasperTest1.csproj...
info :   GET https://api.nuget.org/v3-flatcontainer/casper.network.sdk/index.json
info :   NotFound https://api.nuget.org/v3-flatcontainer/casper.network.sdk/index.json 885ms
error: NU1101: Unable to find package Casper.Network.SDK. No packages exist with this id in source(s): nuget.org
error: Package 'Casper.Network.SDK' is incompatible with 'all' frameworks in project '/Users/room/Projects/CasperTest1/CasperTest1/CasperTest1.csproj'.

**Comment by davidatwhiletrue** [comment]
Hi Thênh Thang. The beta package is not yet published in nuget.org. We'll publish it soon. Currently, version 0.9.4-beta it's published in GitHub Packages. 

Follow these instructions to add the GH Packags repository to your dotnet installation:
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-nuget-registry

Alternatively, you can clone the source code repo and build the library from the master branch.

David
