### ISSUE TITLE
PublicKey is still using checksummed addresses

### ISSUE THREAD

**Issue by GuybrushX** [make-software/casper-net-sdk#25]
**What happened?**
`PublicKey` - more specifically `ToAccountHex()` which is also used by `ToString()` - is using checksummed addresses which were deactivated and postponed to another future version (AFAIK).

Using checksummed addresses causes issues on e. g. cspr.live -> Wallet -> Transfer CSPR -> Casper Signer will error out if using checksummed addresses. casperholders.io has the same issue, too.

I've also used Wireshark to check if the checksummed addresses are returned by RPC calls and saw that RPC responses contain lower-cased addresses which I think is correct -> the Casper .NET SDK is the reason.

Maybe this issue needs to be raised to the Casper Signer and/or cspr.live, too to handle checksummed addresses more carefully and simply lower-case public keys.

Sample code to reproduce:
```csharp
PublicKey publicKey = PublicKey.FromHexString("0154a4d3a719b76861e56dcd4b5a6ef43814ef3c512346bd6af1d07dc69401c1e9");
Trace.WriteLine(publicKey);
```

Output (mixed-case):
```console
0154a4d3A719b76861E56DcD4b5A6Ef43814eF3C512346bD6af1D07DC69401C1E9
```

**What did you expect to happen?**
Expected output (lower-case):
```console
0154a4d3a719b76861e56dcd4b5a6ef43814ef3c512346bd6af1d07dc69401c1e9
```

All public keys should be lower case and not using checksummed addresses to avoid confusion and issues as long as it is not officially enabled again.

**Are you willing to submit a pull request to fix this bug?**
No since I think I would miss something anyway and I'm not sure if this is considered as an issue or not.

An easy and probably hacky fix without running tests etc. could look like this:

Change line 112 in [CEP57Checksum.cs](https://github.com/make-software/casper-net-sdk/blob/master/Casper.Network.SDK/Utils/CEP57Checksum.cs#L112):
```csharp
// Before
return sb.ToString();

// After
return sb.ToString().ToLower();
```

I didn't run any tests and it is very likely that this breaks something so be warned.

**Comment by davidatwhiletrue** [comment]
Thanks @GuybrushX  for your detailed explanation.
While Casper nodes return lower-case addresses, the nodes accept and verify correctness of checksummed public keys and account hashes. 
Thus, it make sense to keep generating checksummed values and the application integrating the SDK can always do `.ToLower()` if needed.
