### ISSUE TITLE
Failure to deserialize the System proposed switch block

### ISSUE THREAD

**Issue by mrkara** [make-software/casper-net-sdk#37]
Try to deserialize the "System proposed switch block" -> the .Net SDK fails because the Proposer is normally a PublicKey but now it is "00" which is invalid.

Reported by "X Y" from the community. He is willing to provide more info if needed.

**Comment by davidatwhiletrue** [comment]
Thanks @mrkara for opening this issue.

Note: this is the problematic block: https://cspr.live/block/1562c81ea1623b6c882370b4a659b797e06e30ddbc0053b6b0d3a1aef71c6d33
