### ISSUE TITLE
GetDeploy(DeployHash)  info_get_deploy_result

### ISSUE THREAD

**Issue by stormeye2000** [make-software/casper-net-sdk#41]
**What happened?**

A StandardTransfer is executed
A block added event with the deploy hash is waited for
The deploy result is then retrieved
The session object of the deploy result is then analysed

The target argument type is ByteArray

**What did you expect to happen?**

The expected argument type is expected to be of type PublicKey

I can see that it is being stored as an AccountHash, which in turn is being converted to a CLType of ByteArray
It needs to be stored as a PublicKey to bring in line with the other SDK's

Thanks

Carl Norburn

**Comment by davidatwhiletrue** [comment]
hey @stormeye2000 . If I understood correctly the issue, you expect to see on `target` runtime argument a PublicKey type for a standard transfer. But, the SDK is not converting from one type to another. And for some deploys `target` is a byte array and for some other transfer deploys it's a public key. Examples:

target is PublicKey
https://cspr.live/deploy/d43cbf081f81a6984604285b14e9ccd607191becf111e15811e0245f99cadd24


target is ByteArray
https://cspr.live/deploy/a2c77dafcb5ad5cf5ea70689dabcf59574aec6fddcb9cd609b0dcf0dabc237f1

In the latter example, I don't think the SDK can convert an account hash to a public key.

**Comment by stormeye2000** [comment]
More info it helps:

Test feature [here](https://github.com/stormeye2000/cspr-sdk-standard-tests-net/blob/main/CsprSdkStandardTestsNet/Test/Features/deploys.feature)

Test code [here](https://github.com/stormeye2000/cspr-sdk-standard-tests-net/blob/main/CsprSdkStandardTestsNet/Test/Steps/Deploys.cs)

Thanks

**Comment by davidatwhiletrue** [comment]
Hi @stormeye2000 , As described above, a native transfer can use a public key or an account hash as `target` input argument. 
`DeployTemplates.StandardTransfer() uses the second, which is ok. But it does not pass your test.

If you cannot modify the test to check that `target` is a `public key` or `account hash`, then you can build the transfer deploy without a template like this:

```
        var session = new TransferDeployItem()
        {
            RuntimeArgs = new List<NamedArg>
            {
                new("amount", CLValue.U512(_contextMap.Get<BigInteger>(StepConstants.TRANSFER_AMOUNT))),
                new("target", _contextMap.Get<PublicKey>(StepConstants.RECEIVER_KEY)),
                new("id", CLValue.Option(CLValue.U64(0))),
            }
        };
        var payment = new ModuleBytesDeployItem(100_000_000);
        var header = new DeployHeader()
        {
            Account = senderKey.PublicKey,
            Timestamp = DateUtils.ToEpochTime(DateTime.UtcNow),
            Ttl = (ulong)TimeSpan.FromMinutes(_contextMap.Get<ulong>(StepConstants.TTL)).TotalMilliseconds,
            ChainName = chainName,
            GasPrice = 1
        };
        var deploy = new Deploy(header, payment, session);
```

This type of deploy meets the criteria to pass your test.

**Comment by stormeye2000** [comment]
The above fixes the issue, thanks.
Please close
