### ISSUE TITLE
GetAccountBalance(accountMainPurse, stateRootHash)  state_get_balance

### ISSUE THREAD

**Issue by stormeye2000** [make-software/casper-net-sdk#42]
**What happened?**

The SDK GetAccountBalance(accountMainPurse, stateRootHash) returns a null Merkle proof

**What did you expect to happen?**

Expected a valid Merkle proof to be returned

Thanks

Carl Norburn

**Comment by davidatwhiletrue** [comment]
There was a change on 1.5 to introduce a new RPC method to get an account balance: `query_balance`. See [here](https://github.com/casper-network/casper-node/pull/2868).

New endpoint does not return `merkle_proof`. 

We may consider to remove the property from `GetBalanceResult`.

**Comment by davidatwhiletrue** [comment]
Closing this ticket since any of the `GetAccountBalance` versions returns `merkle_proof` when using `query_balance` RPC method.
