### ISSUE TITLE
DeployTemplates ContractDeploy can't add NamedArgs

### ISSUE THREAD

**Issue by stormeye2000** [make-software/casper-net-sdk#44]
**What happened?**

Tried to add user defined NamedArgs to a ContractDeploy
Could not see a way to do this:

`       
 var paymentArgs = new List<NamedArg>{

            new ("amount", CLValue.U512(payment)), 

            new ("token_decimals", CLValue.U8(tokenDecimals)), 

            new ("token_name", CLValue.String(tokenName)),

            new ("token_symbol", CLValue.String(tokenSymbol)), 

            new ("token_total_supply", CLValue.U256(tokenTotalSupply))
 `

**What did you expect to happen?**

The above list of NamedArgs can be added to the ContractDeploy

Thanks

Carl Norburn

**Comment by davidatwhiletrue** [comment]
Try with:
```
            var payment = 1000000000L;
            byte tokenDecimals = 0x09;
            var tokenName = "SDK";
            var tokenSymbol = "SDK";
            var tokenTotalSupply = 1_000_000_000_000_000_000L;
            
            var runtimeArgs = new List<NamedArg>
            {
                new("amount", CLValue.U512(payment)),
                new("token_decimals", CLValue.U8(tokenDecimals)),
                new("token_name", CLValue.String(tokenName)),
                new("token_symbol", CLValue.String(tokenSymbol)),
                new("token_total_supply", CLValue.U256(tokenTotalSupply))
            };
```

**Comment by stormeye2000** [comment]
@davidatwhiletrue what I meant was, once I've created the NamedArg list, how do I then add it to the deploy session?

https://github.com/stormeye2000/cspr-sdk-standard-tests-net/blob/1ba6b94e96b4898c9a7b654bf4941252ec53c469/CsprSdkStandardTestsNet/Test/Steps/WasmStepDefinitions.cs#L72

**Comment by stormeye2000** [comment]
The above fixes the issue, thanks
Please close
