### ISSUE TITLE
Not a bug, a missing feature: Account Info Standard Support

### ISSUE THREAD

**Issue by GuybrushX** [make-software/casper-net-sdk#48]
**What happened?**
It looks like the Account Info Standard is not directly supported by the .Net SDK.

**What did you expect to happen?**
Support of the Account Info Standard in the .Net SDK to make it easier to retrieve that info instead of doing this manually.

Two possible solutions:
1. A quick and easy implementation would be to provide the URL to the JSON file only.
2. (Preferred) A much better but ideal solution would be a fully type-safe wrapper around the JSON file.

For the contract hashes:
I *think* it would be OK to store them for the MainNet and TestNet since they shouldn't change.

But for internal test networks I think it also has to be configurable or be passed as an optional parameter somehow.

**Are you willing to submit a pull request to fix this bug?**
Maybe, I'll have to get some spare time to dig deeper here how a potential implementation could look like.
-> Better don't count on it and I think you have all the skills and knowledge at hand already so it should be pretty straightforward :-)

**Comment by davidatwhiletrue** [comment]
hey @GuybrushX it's a good idea. I would implement this in the [clients ](https://github.com/make-software/casper-net-sdk-clients) library instead of the main SDK. In fact, it would be a contract client. And we could add support for both, to call `set-url` as well as to `get-url`.

If you agree, can you move the issue there?

**Comment by GuybrushX** [comment]
Thanks for the fast reply :-)

It looks like I can't move it directly but I created the issue again in the reference repository:
https://github.com/make-software/casper-net-sdk-clients/issues/10
